// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obrinjqklnrokqhgygyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9icmluanFrbG5yb2txaGd5Z3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDQ5ODQsImV4cCI6MjA2ODE4MDk4NH0._tSdNkmVwHC0E3nKitBESvaEB8RDngT298UNrGO-9Cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});